
USER_CONFIGURATIONS   = debug release special
USER_REBUILD_CRITERIA = 

MSG_FLUSH = "gestern\ telefon"

include $(DEVELOPMENT_BASE)/make/rules.generic
include $(DEVELOPMENT_BASE)/make/rules.debug
include $(DEVELOPMENT_BASE)/make/rules.msg
include $(DEVELOPMENT_BASE)/make/rules.help


