
#USER_CONFIGURATIONS   = debug release special
#USER_REBUILD_CRITERIA = 
#
#MSG_FLUSH = "gestern\ telefon"
#
DEVELOPMENT_BASE = ../..
#
#include $(DEVELOPMENT_BASE)/makeIt/rules.generic
#include $(DEVELOPMENT_BASE)/makeIt/rules.debug
#include $(DEVELOPMENT_BASE)/makeIt/rules.msg
#include $(DEVELOPMENT_BASE)/makeIt/rules.help
#

mk_rule_base = ../../makeIt

include $(mk_rule_base)/rules.base

