
TARGET_doc = Some project for\\n testing make files
#SOURCE_FILES        = 
SOURCE_FILES.shared = bla.f
IGNORE_FILES        =
IGNORE_FILES.static = testinger.for


FC_PP_DEFINES     =
FC_INCLUDE_DIRS   =
FC_FLAGS          =
FC_CFLAGS         = 
FC_CFLAGS.debug   = $(fc_g)
FC_CFLAGS.release = $(fc_O3)

FC_LIBRARY_DIRS   = 
FC_LIBRARIES      = 
FC_LFLAGS         =
FC_LINK_INPUT     =

MAKEIT_DIR = ../
include $(MAKEIT_DIR)/mk.compilation
include $(MAKEIT_DIR)/mk.fortran

