
#SOURCE_FILES = testinger.for
#IGNORE_FILES = $(wildcard *.for)
TARGET_doc = Some project for\\n testing make files

testinger.debug   = $(fc_D)DEBUG=1 $(fc_pic)
testinger.release = $(fc_D)RELEASE=1


MAKEIT_DIR = ../
include $(MAKEIT_DIR)/rules.compilation
include $(MAKEIT_DIR)/rules.fortran

